"""
CCX (Toffoli) Pedersen Haar-averaged Gate Fidelity
------------------------------------------------------------------------
OPTION A: Rb 66 D_{5/2} + Cs 76 D_{3/2} d-state Foerster pair
          at a = 5.00 um
------------------------------------------------------------------------

Recomputes the average gate fidelity of the three-qubit Rydberg CCX gate
using the Pedersen Haar-averaged formula instead of the computational-
basis average of Yu et al.:

    L. H. Pedersen, N. M. Moller, K. Molmer,
    "Fidelity of quantum operations",
    Phys. Lett. A 367, 47 (2007).

Pedersen's formula (his Eqs. (3) and (5), restricted to the d = 2^n = 8
computational subspace S of the full 3 x 3 x 4 = 36-dim Cs x Cs x Rb
simulator, with projector P onto S):

    F_bar = (1 / [d(d+1)]) * [ sum_k Tr(M_k^dag M_k) + sum_k |Tr(M_k)|^2 ]

with Kraus operators M_k = P U_0^dag G_k P, where {G_k} is any Kraus
decomposition of the full-space CPTP map E generated by the Lindblad
propagator.  Equivalently (Nielsen/Horodecki form used by QuTiP),

    F_bar = (d * F_pro + 1) / (d + 1),
    F_pro = (1/d^2) * sum_{i,j} <pi(i)| E(|i><j|) |pi(j)>,

where U_0 |i> = |pi(i)> is the CCX permutation on the computational
basis: target flips only when both controls are in |1>.

All physical parameters (interaction strengths, ARC-computed lifetimes,
pulse timings) are taken verbatim from ``ccx_average_gate_fidelity.py``.
"""

import numpy as np

import qutip
from triqg.atoms import CsAtom, RbAtom, DIMS, composite_basis_state
from triqg.pulses import omega_cc, omega_t1, omega_t2
from triqg.hamiltonian import build_ccx_hamiltonian
from triqg.decoherence import build_collapse_operators
from triqg.solver import simulate
from triqg.analysis import state_fidelity, average_gate_fidelity
from triqg.pedersen import (
    build_permutation_unitary,
    choi_on_subspace_via_mesolve,
    pedersen_average_fidelity_from_choi,
)

# =====================================================================
# Physical parameters (copied verbatim from ccx_average_gate_fidelity.py)
# =====================================================================
omega_cc_amp = 2 * np.pi * 100     # Cs control pi-pulse Rabi freq [rad/us]
omega_t_amp = 2 * np.pi * 50       # Rb target sub-pulse Rabi freq [rad/us]

T_cc = np.pi / omega_cc_amp        # 5 ns control pi-pulse
T_t = np.pi / omega_t_amp          # 10 ns target sub-pulse

# Lattice geometry
a_um = 5.00
r_DA = a_um / np.sqrt(2)
r_AA = a_um * np.sqrt(2)

# Ireland et al. 2024 Foerster coefficients
C3_tilde = 22.84
C6_CsCs = -692.9
V_ct_MHz = 1000.0 * C3_tilde / r_DA**3
V_cc_MHz = 1000.0 * C6_CsCs / r_AA**6
V_ct = 2 * np.pi * V_ct_MHz
V_cc = 2 * np.pi * V_cc_MHz

# ARC lifetimes at T = 300 K
gamma_r = 1.0 / 142.73
gamma_R = 1.0 / 134.87
gamma_P = 1.0 / 0.131

args = {
    "omega_cc_amp": omega_cc_amp,
    "omega_t_amp": omega_t_amp,
    "T_cc": T_cc,
    "T_t": T_t,
}

# =====================================================================
# Hamiltonian, collapse operators, total time
# =====================================================================
H = build_ccx_hamiltonian(V_ct, V_cc=V_cc)
c_ops = build_collapse_operators(gamma_r, gamma_R, gamma_P)

t_total = 2 * T_cc + 3 * T_t       # 40 ns

max_freq = max(omega_cc_amp, omega_t_amp) / (2 * np.pi)
max_step = 1.0 / (20 * max_freq)
solver_opts = {
    "nsteps": 100000,
    "max_step": max_step,
    "atol": 1e-10,
    "rtol": 1e-8,
}

# =====================================================================
# Computational-subspace basis and CCX permutation unitary
# =====================================================================
cs = CsAtom()
rb = RbAtom()
ctrl_levels = [cs.level_index["0"], cs.level_index["1"]]
tgt_levels = [rb.level_index["A"], rb.level_index["B"]]

# Index ordering: idx = c1*4 + c2*2 + t
comp_kets = []
labels = []
for c1_bit in range(2):
    for c2_bit in range(2):
        for t_bit in range(2):
            comp_kets.append(
                composite_basis_state(
                    ctrl_levels[c1_bit], ctrl_levels[c2_bit], tgt_levels[t_bit]
                )
            )
            labels.append(
                f"|{c1_bit},{c2_bit},{['A','B'][t_bit]}>"
            )


def ccx_permutation(idx: int) -> int:
    """CCX: target flips iff both controls are |1>."""
    c1 = (idx >> 2) & 1
    c2 = (idx >> 1) & 1
    t = idx & 1
    t_out = t ^ (c1 & c2)
    return (c1 << 2) | (c2 << 1) | t_out


U0 = build_permutation_unitary(comp_kets, ccx_permutation)

# =====================================================================
# (A) Pedersen Haar-averaged fidelity
# =====================================================================
print("CCX Gate Pedersen Haar-averaged Gate Fidelity")
print("Option A: Rb 66 D_5/2 + Cs 76 D_3/2 at a =", a_um, "um")
print("=" * 70)
print(f"Simulator dim = {np.prod(DIMS)}, computational dim d = {len(comp_kets)}")
print(f"T_cc = {T_cc*1e3:.3f} ns, T_t = {T_t*1e3:.3f} ns, "
      f"total gate time = {t_total*1e3:.3f} ns")
print(f"V_ct/(2pi) = +{V_ct_MHz:7.3f} MHz, V_cc/(2pi) = {V_cc_MHz:+7.3f} MHz")
print(f"Lifetimes: tau_r={1/gamma_r:.2f} us, tau_R={1/gamma_R:.2f} us, "
      f"tau_P={1/gamma_P:.3f} us\n")

print("Computing the d^2 = 64 subspace Choi matrix elements "
      "via mesolve on non-Hermitian operator initial conditions...",
      flush=True)
choi = choi_on_subspace_via_mesolve(
    H, c_ops, t_total, comp_kets, args=args, options=solver_opts,
    verbose=True,
)
F_bar_ped, F_pro, survival = pedersen_average_fidelity_from_choi(choi, U0)
print("... done.\n")

# =====================================================================
# (B) Original basis-averaged fidelity for comparison
# =====================================================================
print("For comparison, recomputing the basis-averaged fidelity "
      "F_bar_basis = (1/d) sum_i F_i ...")
tlist = np.linspace(0, t_total, 500)
mesolve_opts = {"store_final_state": True, "nsteps": 100000, "max_step": max_step}
fidelity_pairs = []
per_input_fidelity = []

for i, psi_in in enumerate(comp_kets):
    psi_ideal = comp_kets[ccx_permutation(i)]
    print(f"  [{i+1}/8] input {labels[i]} -> ideal {labels[ccx_permutation(i)]}", end=" ", flush=True)
    result = simulate(
        method="mesolve",
        H=H,
        psi0=psi_in,
        tlist=tlist,
        c_ops=c_ops,
        e_ops=[],
        options=mesolve_opts,
        args=args,
    )
    fid = state_fidelity(result.final_state, psi_ideal)
    fidelity_pairs.append((result.final_state, psi_ideal))
    per_input_fidelity.append(fid)
    print(f"F_k = {fid:.6f}")
F_bar_basis = average_gate_fidelity(fidelity_pairs)

# =====================================================================
# (C) Cross-check via qutip.average_gate_fidelity on the projected super-op
# =====================================================================
d = 8
comp_dims = [2, 2, 2]
G_comp = np.zeros((d * d, d * d), dtype=complex)
for j in range(d):
    for i in range(d):
        G_comp[:, j * d + i] = choi[i, j, :, :].reshape((d * d,), order="F")
G_comp_qobj = qutip.Qobj(
    G_comp,
    dims=[[comp_dims, comp_dims], [comp_dims, comp_dims]],
    superrep="super",
)
U0_qobj = qutip.Qobj(U0, dims=[comp_dims, comp_dims])
F_bar_qutip = qutip.average_gate_fidelity(G_comp_qobj, target=U0_qobj)

# =====================================================================
# Report
# =====================================================================
print("\n" + "=" * 70)
print("Summary for the CCX gate at a = 5.00 um (Option A Foerster pair)")
print("=" * 70)
print(f"  Computational-subspace survival T_P       = {survival:.6f}")
print(f"    (1 - T_P = {1 - survival:.3e}: residual leakage to |r>, |P>, |R>)")
print()
print("Per-input basis fidelities F_k (Yu et al. Eq. (7) integrand):")
for lbl, F_k in zip(labels, per_input_fidelity):
    print(f"    {lbl:<14} F_k = {F_k:.6f}")
print(f"  -> F_bar_basis  = (1/8) sum_k F_k       = {F_bar_basis:.6f}   "
      f"(infidelity {1-F_bar_basis:.3e})")
print()
print("Pedersen Haar-averaged (PLA 367, 47 (2007), Eq. (5)):")
print(f"  Process fidelity  F_pro                    = {F_pro:.6f}")
print(f"  F_bar_Pedersen  = (d*F_pro + 1)/(d+1)    = {F_bar_ped:.6f}   "
      f"(infidelity {1-F_bar_ped:.3e})")
print(f"  Cross-check via qutip.average_gate_fidelity = {F_bar_qutip:.6f}  "
      f"(should match to ~1e-10)")
print("=" * 70)
