"""
OR Gate Pedersen Haar-averaged Gate Fidelity (Super-Gaussian Pulse)
------------------------------------------------------------------------
OPTION A: Rb 66 D_{5/2} + Cs 76 D_{3/2} d-state Foerster pair
          at a = 5.00 um,  Omega_R = 3.5 * Omega_p
------------------------------------------------------------------------

Recomputes the average gate fidelity of the three-qubit Rydberg OR gate
using the Pedersen Haar-averaged formula instead of the computational-
basis average of Yu et al.:

    L. H. Pedersen, N. M. Moller, K. Molmer,
    "Fidelity of quantum operations",
    Phys. Lett. A 367, 47 (2007).

Pedersen's formula (his Eqs. (3) and (5), restricted to the d = 2^n = 8
computational subspace S of the full 3 x 3 x 4 = 36-dim Cs x Cs x Rb
simulator, with projector P onto S):

    F_bar = (1 / [d(d+1)]) * [ sum_k Tr(M_k^dag M_k) + sum_k |Tr(M_k)|^2 ]

with Kraus operators M_k = P U_0^dag G_k P, where {G_k} is any Kraus
decomposition of the full-space CPTP map E generated by the Lindblad
propagator.  Equivalently (Nielsen/Horodecki form used by QuTiP),

    F_bar = (d * F_pro + 1) / (d + 1),
    F_pro = (1/d^2) * sum_{i,j} <pi(i)| E(|i><j|) |pi(j)>,

where U_0 |i> = |pi(i)> is the OR permutation on the computational basis.

Unlike the basis-averaged fidelity F_bar_basis = (1/d) sum_i F_i that
ignores off-diagonal coherence, Pedersen's formula averages over Haar-
random pure superpositions and therefore penalizes random phases and
coherence decay in addition to population error.

This script evaluates Pedersen's formula via one call to
``qutip.propagator`` on the full 36-dim Liouvillian, followed by a clean
projection onto the 8-dim computational subspace (see ``triqg.pedersen``).

All physical parameters (pulse shape, detuning, ARC-computed lifetimes,
V_ct and V_cc from the Ireland et al. 2024 Foerster channel) are taken
verbatim from ``or_average_gate_fid_gaussian.py`` so the numbers are
directly comparable.
"""

import numpy as np

import qutip
from triqg.atoms import CsAtom, RbAtom, DIMS, composite_basis_state
from triqg.pulses import omega_c, omega_gaussian, omega_R, compute_pulse_area
from triqg.hamiltonian import build_hamiltonian
from triqg.decoherence import build_collapse_operators
from triqg.solver import simulate
from triqg.analysis import state_fidelity, average_gate_fidelity
from triqg.pedersen import (
    build_permutation_unitary,
    choi_on_subspace_via_mesolve,
    pedersen_average_fidelity_from_choi,
)

# =====================================================================
# Physical parameters (copied verbatim from or_average_gate_fid_gaussian.py)
# =====================================================================
omega_c_amp = 2 * np.pi * 50       # Cs control Rabi frequency [rad/us]
omega_p_amp = 2 * np.pi * 50.0     # Rb target two-photon probe amplitude
omega_R_amp = 3.5 * omega_p_amp    # Omega_R = 3.5 * Omega_p

delta = 2 * np.pi * 500            # Two-photon detuning Delta [rad/us]

# Lattice geometry (rotated lattice, a in um)
a_um = 5.0
r_DA = a_um / np.sqrt(2)
r_AA = a_um * np.sqrt(2)

# Ireland et al. 2024 Foerster coefficients for Rb 66 D_{5/2} + Cs 76 D_{3/2}
C3_tilde = 22.84                   # GHz * um^3
C6_CsCs = -692.9                   # GHz * um^6 (signed)
V_ct_MHz = 1000.0 * C3_tilde / r_DA**3
V_cc_MHz = 1000.0 * C6_CsCs / r_AA**6 * 0.0
V_ct = 2 * np.pi * V_ct_MHz
V_cc = 2 * np.pi * V_cc_MHz

# Pulse timings
T_c = np.pi / omega_c_amp          # 10 ns control pi-pulse
T_f = 0.15                         # 150 ns super-Gaussian half-window
sigma = 0.001771                   # super-Gaussian width

# ARC lifetimes at T = 300 K (Sibalic et al. 2017 + Beterov et al. 2009)
gamma_r = 1.0 / 142.73             # Cs |r> = |76 D_{3/2}>
gamma_R = 1.0 / 134.87             # Rb |R> = |66 D_{5/2}>
gamma_P = 1.0 / 0.131              # Rb |P> = |7 P_{3/2}> (paper value)

args = {
    "omega_c_amp": omega_c_amp,
    "omega_p_amp": omega_p_amp,
    "omega_R_amp": omega_R_amp,
    "T_c": T_c,
    "T_f": T_f,
    "sigma": sigma,
}

# =====================================================================
# Verify pulse area (sanity check vs the original script)
# =====================================================================
area = compute_pulse_area(omega_gaussian, delta, T_c, T_c + 2 * T_f, args)
print(f"Effective two-photon pulse area: {area:.4f} (target: pi = {np.pi:.4f})")

# =====================================================================
# Hamiltonian, collapse operators, total time
# =====================================================================
H = build_hamiltonian(delta, V_ct, pulse_p=omega_gaussian, V_cc=V_cc)
c_ops = build_collapse_operators(gamma_r, gamma_R, gamma_P)

t_total = 2 * T_c + 2 * T_f         # 320 ns

solver_opts = {"nsteps": 100000, "atol": 1e-10, "rtol": 1e-8}

# =====================================================================
# Computational-subspace basis and OR permutation unitary
# =====================================================================
cs = CsAtom()
rb = RbAtom()
ctrl_levels = [cs.level_index["0"], cs.level_index["1"]]  # = [0, 1]
tgt_levels = [rb.level_index["A"], rb.level_index["B"]]   # = [0, 1]

# Index ordering: idx = c1*4 + c2*2 + t, with c1,c2 in {0,1} and t in {A,B}
comp_kets = []
labels = []
for c1_bit in range(2):
    for c2_bit in range(2):
        for t_bit in range(2):
            comp_kets.append(
                composite_basis_state(
                    ctrl_levels[c1_bit], ctrl_levels[c2_bit], tgt_levels[t_bit]
                )
            )
            labels.append(
                f"|{c1_bit},{c2_bit},{['A','B'][t_bit]}>"
            )


def or_permutation(idx: int) -> int:
    """OR gate: target flips when at least one control is in |1>."""
    c1 = (idx >> 2) & 1
    c2 = (idx >> 1) & 1
    t = idx & 1
    t_out = t ^ (c1 | c2)
    return (c1 << 2) | (c2 << 1) | t_out


U0 = build_permutation_unitary(comp_kets, or_permutation)

# =====================================================================
# (A) Pedersen Haar-averaged fidelity
# =====================================================================
print("\nOR Gate Pedersen Haar-averaged Gate Fidelity")
print("Option A: Rb 66 D_5/2 + Cs 76 D_3/2 at a =", a_um, "um,",
      "Omega_R/Omega_p = 3.5")
print("=" * 70)
print(f"Simulator dim = {np.prod(DIMS)}, computational dim d = {len(comp_kets)}")
print(f"T_c = {T_c*1e3:.3f} ns, T_f = {T_f*1e3:.3f} ns, "
      f"total gate time = {t_total*1e3:.3f} ns")
print(f"V_ct/(2pi) = +{V_ct_MHz:7.3f} MHz, V_cc/(2pi) = {V_cc_MHz:+7.3f} MHz")
print(f"Lifetimes: tau_r={1/gamma_r:.2f} us, tau_R={1/gamma_R:.2f} us, "
      f"tau_P={1/gamma_P:.3f} us\n")

print("Computing the d^2 = 64 subspace Choi matrix elements "
      "via mesolve on non-Hermitian operator initial conditions...",
      flush=True)
choi = choi_on_subspace_via_mesolve(
    H, c_ops, t_total, comp_kets, args=args, options=solver_opts,
    verbose=True,
)
F_bar_ped, F_pro, survival = pedersen_average_fidelity_from_choi(choi, U0)
print("... done.\n")

# =====================================================================
# (B) For comparison: original basis-averaged fidelity (Yu et al. Eq. (7))
# =====================================================================
print("For comparison, recomputing the basis-averaged fidelity "
      "F_bar_basis = (1/d) sum_i F_i ...")
tlist = np.linspace(0, t_total, 500)
mesolve_opts = {"store_final_state": True, "nsteps": 10000}
fidelity_pairs = []
per_input_fidelity = []

for i, psi_in in enumerate(comp_kets):
    psi_ideal = comp_kets[or_permutation(i)]
    print(f"  [{i+1}/8] input {labels[i]} -> ideal {labels[or_permutation(i)]}", end=" ", flush=True)
    result = simulate(
        method="mesolve",
        H=H,
        psi0=psi_in,
        tlist=tlist,
        c_ops=c_ops,
        e_ops=[],
        options=mesolve_opts,
        args=args,
    )
    fid = state_fidelity(result.final_state, psi_ideal)
    fidelity_pairs.append((result.final_state, psi_ideal))
    per_input_fidelity.append(fid)
    print(f"F_k = {fid:.6f}")
F_bar_basis = average_gate_fidelity(fidelity_pairs)

# =====================================================================
# (C) Cross-check via qutip.average_gate_fidelity on the projected super-op
# =====================================================================
# Build the projected channel as a qutip super-Qobj in subsystem dims
# [2,2,2] so qutip can interpret the 8-dim computational space as three
# logical qubits and apply Pedersen's formula itself.
d = 8
comp_dims = [2, 2, 2]
G_comp = np.zeros((d * d, d * d), dtype=complex)
for j in range(d):
    for i in range(d):
        # Column-stacking vectorization: (j * d + i) -> operator |i><j|
        G_comp[:, j * d + i] = choi[i, j, :, :].reshape((d * d,), order="F")
G_comp_qobj = qutip.Qobj(
    G_comp,
    dims=[[comp_dims, comp_dims], [comp_dims, comp_dims]],
    superrep="super",
)
U0_qobj = qutip.Qobj(U0, dims=[comp_dims, comp_dims])
F_bar_qutip = qutip.average_gate_fidelity(G_comp_qobj, target=U0_qobj)

# =====================================================================
# Report
# =====================================================================
print("\n" + "=" * 70)
print("Summary for the OR gate at a = 5.00 um (Option A Foerster pair)")
print("=" * 70)
print(f"  Computational-subspace survival T_P       = {survival:.6f}")
print(f"    (1 - T_P = {1 - survival:.3e}: residual leakage to |r>, |P>, |R>)")
print()
print("Per-input basis fidelities F_k (Yu et al. Eq. (7) integrand):")
for lbl, F_k in zip(labels, per_input_fidelity):
    print(f"    {lbl:<14} F_k = {F_k:.6f}")
print(f"  -> F_bar_basis  = (1/8) sum_k F_k       = {F_bar_basis:.6f}   "
      f"(infidelity {1-F_bar_basis:.3e})")
print()
print("Pedersen Haar-averaged (PLA 367, 47 (2007), Eq. (5)):")
print(f"  Process fidelity  F_pro                    = {F_pro:.6f}")
print(f"  F_bar_Pedersen  = (d*F_pro + 1)/(d+1)    = {F_bar_ped:.6f}   "
      f"(infidelity {1-F_bar_ped:.3e})")
print(f"  Cross-check via qutip.average_gate_fidelity = {F_bar_qutip:.6f}  "
      f"(should match to ~1e-10)")
print()
print("Note: F_bar_Pedersen < F_bar_basis is generic when the channel")
print("has off-diagonal (coherence) errors in addition to population error.")
print("=" * 70)
